---
- name: my first playbook
  hosts: west_server
  become: true
  tasks:

    - name: "updating... repository index"
      ansible.builtin.yum:
        update_cache: yes
    
    - name: "installing ... apache2 package"
      ansible.builtin.yum:
        name: apache2
        state: latest
...
