---
- name: my first playbook
  hosts: west_server
  become: true
  tasks:

    - name: update repository index
      ansible.builtin.yum:
        update_cache: yes
    
    - name: install apache2 package
      ansible.builtin.yum:
        name: apache2
...
